.PHONY: all clean 

all: expression_mRNA_17-Aug-2014.txt

expression_mRNA_17-Aug-2014.txt:
	wget https://storage.googleapis.com/linnarsson-lab-www-blobs/blobs/cortex/expression_mRNA_17-Aug-2014.txt

clean:
	-rm expression_mRNA_17-Aug-2014.txt
	-rm zeisel.h5ad
